name: 'Kiosk Pro version file'
description: 'Create a version file for the Kiosk Pro app'
author: 'Eric Londaits for Imaginary gGmbH'

branding:
  icon: 'file-text'
  color: 'orange'

# Define your inputs here.
inputs:
  filename:
    description: 'Filename of the version file to create.'
    required: false
    default: 'kiosk-pro-version.xml'
  version:
    description: 'Version number (must be an integer number).'
    required: true
  zip:
    description:
      'Filename or full URL to the .zip file containing the files corresponding
      to the version.'
    required: true
  clear-previous-content:
    description:
      'Set to "true" to remove existing files from the Kiosk App before
      installing the new version.'
    required: false
    default: 'false'

# Define your outputs here.
outputs:
  filepath:
    description: 'Path to the version file created.'

runs:
  using: node20
  main: dist/index.js
